server:
  port: 9292

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:beanvalidation
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG